// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetKmsAsymmetricEncryptionKey
    {
        public static Task<GetKmsAsymmetricEncryptionKeyResult> InvokeAsync(GetKmsAsymmetricEncryptionKeyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetKmsAsymmetricEncryptionKeyResult>("yandex:index/getKmsAsymmetricEncryptionKey:getKmsAsymmetricEncryptionKey", args ?? new GetKmsAsymmetricEncryptionKeyArgs(), options.WithDefaults());

        public static Output<GetKmsAsymmetricEncryptionKeyResult> Invoke(GetKmsAsymmetricEncryptionKeyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetKmsAsymmetricEncryptionKeyResult>("yandex:index/getKmsAsymmetricEncryptionKey:getKmsAsymmetricEncryptionKey", args ?? new GetKmsAsymmetricEncryptionKeyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetKmsAsymmetricEncryptionKeyArgs : global::Pulumi.InvokeArgs
    {
        [Input("asymmetricEncryptionKeyId", required: true)]
        public string AsymmetricEncryptionKeyId { get; set; } = null!;

        [Input("deletionProtection")]
        public bool? DeletionProtection { get; set; }

        [Input("description")]
        public string? Description { get; set; }

        [Input("encryptionAlgorithm")]
        public string? EncryptionAlgorithm { get; set; }

        [Input("folderId")]
        public string? FolderId { get; set; }

        [Input("labels")]
        private Dictionary<string, string>? _labels;
        public Dictionary<string, string> Labels
        {
            get => _labels ?? (_labels = new Dictionary<string, string>());
            set => _labels = value;
        }

        [Input("name")]
        public string? Name { get; set; }

        public GetKmsAsymmetricEncryptionKeyArgs()
        {
        }
        public static new GetKmsAsymmetricEncryptionKeyArgs Empty => new GetKmsAsymmetricEncryptionKeyArgs();
    }

    public sealed class GetKmsAsymmetricEncryptionKeyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("asymmetricEncryptionKeyId", required: true)]
        public Input<string> AsymmetricEncryptionKeyId { get; set; } = null!;

        [Input("deletionProtection")]
        public Input<bool>? DeletionProtection { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("encryptionAlgorithm")]
        public Input<string>? EncryptionAlgorithm { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetKmsAsymmetricEncryptionKeyInvokeArgs()
        {
        }
        public static new GetKmsAsymmetricEncryptionKeyInvokeArgs Empty => new GetKmsAsymmetricEncryptionKeyInvokeArgs();
    }


    [OutputType]
    public sealed class GetKmsAsymmetricEncryptionKeyResult
    {
        public readonly string AsymmetricEncryptionKeyId;
        public readonly string CreatedAt;
        public readonly bool? DeletionProtection;
        public readonly string? Description;
        public readonly string? EncryptionAlgorithm;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableDictionary<string, string>? Labels;
        public readonly string? Name;
        public readonly string Status;

        [OutputConstructor]
        private GetKmsAsymmetricEncryptionKeyResult(
            string asymmetricEncryptionKeyId,

            string createdAt,

            bool? deletionProtection,

            string? description,

            string? encryptionAlgorithm,

            string folderId,

            string id,

            ImmutableDictionary<string, string>? labels,

            string? name,

            string status)
        {
            AsymmetricEncryptionKeyId = asymmetricEncryptionKeyId;
            CreatedAt = createdAt;
            DeletionProtection = deletionProtection;
            Description = description;
            EncryptionAlgorithm = encryptionAlgorithm;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Name = name;
            Status = status;
        }
    }
}
