// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ComputeDiskPlacementGroup struct {
	pulumi.CustomResourceState

	CreatedAt   pulumi.StringOutput    `pulumi:"createdAt"`
	Description pulumi.StringPtrOutput `pulumi:"description"`
	FolderId    pulumi.StringOutput    `pulumi:"folderId"`
	Labels      pulumi.StringMapOutput `pulumi:"labels"`
	Name        pulumi.StringOutput    `pulumi:"name"`
	Status      pulumi.StringOutput    `pulumi:"status"`
	Zone        pulumi.StringPtrOutput `pulumi:"zone"`
}

// NewComputeDiskPlacementGroup registers a new resource with the given unique name, arguments, and options.
func NewComputeDiskPlacementGroup(ctx *pulumi.Context,
	name string, args *ComputeDiskPlacementGroupArgs, opts ...pulumi.ResourceOption) (*ComputeDiskPlacementGroup, error) {
	if args == nil {
		args = &ComputeDiskPlacementGroupArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource ComputeDiskPlacementGroup
	err := ctx.RegisterResource("yandex:index/computeDiskPlacementGroup:ComputeDiskPlacementGroup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetComputeDiskPlacementGroup gets an existing ComputeDiskPlacementGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetComputeDiskPlacementGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ComputeDiskPlacementGroupState, opts ...pulumi.ResourceOption) (*ComputeDiskPlacementGroup, error) {
	var resource ComputeDiskPlacementGroup
	err := ctx.ReadResource("yandex:index/computeDiskPlacementGroup:ComputeDiskPlacementGroup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ComputeDiskPlacementGroup resources.
type computeDiskPlacementGroupState struct {
	CreatedAt   *string           `pulumi:"createdAt"`
	Description *string           `pulumi:"description"`
	FolderId    *string           `pulumi:"folderId"`
	Labels      map[string]string `pulumi:"labels"`
	Name        *string           `pulumi:"name"`
	Status      *string           `pulumi:"status"`
	Zone        *string           `pulumi:"zone"`
}

type ComputeDiskPlacementGroupState struct {
	CreatedAt   pulumi.StringPtrInput
	Description pulumi.StringPtrInput
	FolderId    pulumi.StringPtrInput
	Labels      pulumi.StringMapInput
	Name        pulumi.StringPtrInput
	Status      pulumi.StringPtrInput
	Zone        pulumi.StringPtrInput
}

func (ComputeDiskPlacementGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*computeDiskPlacementGroupState)(nil)).Elem()
}

type computeDiskPlacementGroupArgs struct {
	Description *string           `pulumi:"description"`
	FolderId    *string           `pulumi:"folderId"`
	Labels      map[string]string `pulumi:"labels"`
	Name        *string           `pulumi:"name"`
	Zone        *string           `pulumi:"zone"`
}

// The set of arguments for constructing a ComputeDiskPlacementGroup resource.
type ComputeDiskPlacementGroupArgs struct {
	Description pulumi.StringPtrInput
	FolderId    pulumi.StringPtrInput
	Labels      pulumi.StringMapInput
	Name        pulumi.StringPtrInput
	Zone        pulumi.StringPtrInput
}

func (ComputeDiskPlacementGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*computeDiskPlacementGroupArgs)(nil)).Elem()
}

type ComputeDiskPlacementGroupInput interface {
	pulumi.Input

	ToComputeDiskPlacementGroupOutput() ComputeDiskPlacementGroupOutput
	ToComputeDiskPlacementGroupOutputWithContext(ctx context.Context) ComputeDiskPlacementGroupOutput
}

func (*ComputeDiskPlacementGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**ComputeDiskPlacementGroup)(nil)).Elem()
}

func (i *ComputeDiskPlacementGroup) ToComputeDiskPlacementGroupOutput() ComputeDiskPlacementGroupOutput {
	return i.ToComputeDiskPlacementGroupOutputWithContext(context.Background())
}

func (i *ComputeDiskPlacementGroup) ToComputeDiskPlacementGroupOutputWithContext(ctx context.Context) ComputeDiskPlacementGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComputeDiskPlacementGroupOutput)
}

// ComputeDiskPlacementGroupArrayInput is an input type that accepts ComputeDiskPlacementGroupArray and ComputeDiskPlacementGroupArrayOutput values.
// You can construct a concrete instance of `ComputeDiskPlacementGroupArrayInput` via:
//
//	ComputeDiskPlacementGroupArray{ ComputeDiskPlacementGroupArgs{...} }
type ComputeDiskPlacementGroupArrayInput interface {
	pulumi.Input

	ToComputeDiskPlacementGroupArrayOutput() ComputeDiskPlacementGroupArrayOutput
	ToComputeDiskPlacementGroupArrayOutputWithContext(context.Context) ComputeDiskPlacementGroupArrayOutput
}

type ComputeDiskPlacementGroupArray []ComputeDiskPlacementGroupInput

func (ComputeDiskPlacementGroupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ComputeDiskPlacementGroup)(nil)).Elem()
}

func (i ComputeDiskPlacementGroupArray) ToComputeDiskPlacementGroupArrayOutput() ComputeDiskPlacementGroupArrayOutput {
	return i.ToComputeDiskPlacementGroupArrayOutputWithContext(context.Background())
}

func (i ComputeDiskPlacementGroupArray) ToComputeDiskPlacementGroupArrayOutputWithContext(ctx context.Context) ComputeDiskPlacementGroupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComputeDiskPlacementGroupArrayOutput)
}

// ComputeDiskPlacementGroupMapInput is an input type that accepts ComputeDiskPlacementGroupMap and ComputeDiskPlacementGroupMapOutput values.
// You can construct a concrete instance of `ComputeDiskPlacementGroupMapInput` via:
//
//	ComputeDiskPlacementGroupMap{ "key": ComputeDiskPlacementGroupArgs{...} }
type ComputeDiskPlacementGroupMapInput interface {
	pulumi.Input

	ToComputeDiskPlacementGroupMapOutput() ComputeDiskPlacementGroupMapOutput
	ToComputeDiskPlacementGroupMapOutputWithContext(context.Context) ComputeDiskPlacementGroupMapOutput
}

type ComputeDiskPlacementGroupMap map[string]ComputeDiskPlacementGroupInput

func (ComputeDiskPlacementGroupMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ComputeDiskPlacementGroup)(nil)).Elem()
}

func (i ComputeDiskPlacementGroupMap) ToComputeDiskPlacementGroupMapOutput() ComputeDiskPlacementGroupMapOutput {
	return i.ToComputeDiskPlacementGroupMapOutputWithContext(context.Background())
}

func (i ComputeDiskPlacementGroupMap) ToComputeDiskPlacementGroupMapOutputWithContext(ctx context.Context) ComputeDiskPlacementGroupMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComputeDiskPlacementGroupMapOutput)
}

type ComputeDiskPlacementGroupOutput struct{ *pulumi.OutputState }

func (ComputeDiskPlacementGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ComputeDiskPlacementGroup)(nil)).Elem()
}

func (o ComputeDiskPlacementGroupOutput) ToComputeDiskPlacementGroupOutput() ComputeDiskPlacementGroupOutput {
	return o
}

func (o ComputeDiskPlacementGroupOutput) ToComputeDiskPlacementGroupOutputWithContext(ctx context.Context) ComputeDiskPlacementGroupOutput {
	return o
}

func (o ComputeDiskPlacementGroupOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeDiskPlacementGroup) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o ComputeDiskPlacementGroupOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ComputeDiskPlacementGroup) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o ComputeDiskPlacementGroupOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeDiskPlacementGroup) pulumi.StringOutput { return v.FolderId }).(pulumi.StringOutput)
}

func (o ComputeDiskPlacementGroupOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ComputeDiskPlacementGroup) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

func (o ComputeDiskPlacementGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeDiskPlacementGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ComputeDiskPlacementGroupOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeDiskPlacementGroup) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o ComputeDiskPlacementGroupOutput) Zone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ComputeDiskPlacementGroup) pulumi.StringPtrOutput { return v.Zone }).(pulumi.StringPtrOutput)
}

type ComputeDiskPlacementGroupArrayOutput struct{ *pulumi.OutputState }

func (ComputeDiskPlacementGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ComputeDiskPlacementGroup)(nil)).Elem()
}

func (o ComputeDiskPlacementGroupArrayOutput) ToComputeDiskPlacementGroupArrayOutput() ComputeDiskPlacementGroupArrayOutput {
	return o
}

func (o ComputeDiskPlacementGroupArrayOutput) ToComputeDiskPlacementGroupArrayOutputWithContext(ctx context.Context) ComputeDiskPlacementGroupArrayOutput {
	return o
}

func (o ComputeDiskPlacementGroupArrayOutput) Index(i pulumi.IntInput) ComputeDiskPlacementGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ComputeDiskPlacementGroup {
		return vs[0].([]*ComputeDiskPlacementGroup)[vs[1].(int)]
	}).(ComputeDiskPlacementGroupOutput)
}

type ComputeDiskPlacementGroupMapOutput struct{ *pulumi.OutputState }

func (ComputeDiskPlacementGroupMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ComputeDiskPlacementGroup)(nil)).Elem()
}

func (o ComputeDiskPlacementGroupMapOutput) ToComputeDiskPlacementGroupMapOutput() ComputeDiskPlacementGroupMapOutput {
	return o
}

func (o ComputeDiskPlacementGroupMapOutput) ToComputeDiskPlacementGroupMapOutputWithContext(ctx context.Context) ComputeDiskPlacementGroupMapOutput {
	return o
}

func (o ComputeDiskPlacementGroupMapOutput) MapIndex(k pulumi.StringInput) ComputeDiskPlacementGroupOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ComputeDiskPlacementGroup {
		return vs[0].(map[string]*ComputeDiskPlacementGroup)[vs[1].(string)]
	}).(ComputeDiskPlacementGroupOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ComputeDiskPlacementGroupInput)(nil)).Elem(), &ComputeDiskPlacementGroup{})
	pulumi.RegisterInputType(reflect.TypeOf((*ComputeDiskPlacementGroupArrayInput)(nil)).Elem(), ComputeDiskPlacementGroupArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ComputeDiskPlacementGroupMapInput)(nil)).Elem(), ComputeDiskPlacementGroupMap{})
	pulumi.RegisterOutputType(ComputeDiskPlacementGroupOutput{})
	pulumi.RegisterOutputType(ComputeDiskPlacementGroupArrayOutput{})
	pulumi.RegisterOutputType(ComputeDiskPlacementGroupMapOutput{})
}
