// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about Yandex Cloud Lockbox secret version. For more information,
// see [the official documentation](https://cloud.yandex.com/en/docs/lockbox/).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			mySecretVersion, err := yandex.GetLockBoxSecretVersion(ctx, &GetLockBoxSecretVersionArgs{
//				SecretId:  "some-secret-id",
//				VersionId: pulumi.StringRef("some-version-id"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("mySecretEntries", mySecretVersion.Entries)
//			return nil
//		})
//	}
//
// ```
//
// If you're creating the secret in the same project, then you should indicate `versionId`,
// since otherwise you may refer to a wrong version of the secret
// (e.g. the first version, when it is still empty).
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			mySecret, err := yandex.NewlockboxSecret(ctx, "mySecret", nil)
//			if err != nil {
//				return err
//			}
//			myVersionlockboxSecretVersion, err := yandex.NewlockboxSecretVersion(ctx, "myVersionlockboxSecretVersion", &yandex.lockboxSecretVersionArgs{
//				SecretId: mySecret.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			_ = yandex.GetLockBoxSecretVersionOutput(ctx, GetLockBoxSecretVersionOutputArgs{
//				SecretId:  mySecret.ID(),
//				VersionId: myVersionlockboxSecretVersion.ID(),
//			}, nil)
//			ctx.Export("mySecretEntries", myVersionlockboxSecretVersion.Entries)
//			return nil
//		})
//	}
//
// ```
func GetLockBoxSecretVersion(ctx *pulumi.Context, args *GetLockBoxSecretVersionArgs, opts ...pulumi.InvokeOption) (*GetLockBoxSecretVersionResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetLockBoxSecretVersionResult
	err := ctx.Invoke("yandex:index/getLockBoxSecretVersion:getLockBoxSecretVersion", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLockBoxSecretVersion.
type GetLockBoxSecretVersionArgs struct {
	// The Yandex Cloud Lockbox secret ID.
	SecretId string `pulumi:"secretId"`
	// The Yandex Cloud Lockbox secret version ID.
	VersionId *string `pulumi:"versionId"`
}

// A collection of values returned by getLockBoxSecretVersion.
type GetLockBoxSecretVersionResult struct {
	// List of entries in the Yandex Cloud Lockbox secret version.
	Entries []GetLockBoxSecretVersionEntry `pulumi:"entries"`
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	SecretId  string `pulumi:"secretId"`
	VersionId string `pulumi:"versionId"`
}

func GetLockBoxSecretVersionOutput(ctx *pulumi.Context, args GetLockBoxSecretVersionOutputArgs, opts ...pulumi.InvokeOption) GetLockBoxSecretVersionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetLockBoxSecretVersionResult, error) {
			args := v.(GetLockBoxSecretVersionArgs)
			r, err := GetLockBoxSecretVersion(ctx, &args, opts...)
			var s GetLockBoxSecretVersionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetLockBoxSecretVersionResultOutput)
}

// A collection of arguments for invoking getLockBoxSecretVersion.
type GetLockBoxSecretVersionOutputArgs struct {
	// The Yandex Cloud Lockbox secret ID.
	SecretId pulumi.StringInput `pulumi:"secretId"`
	// The Yandex Cloud Lockbox secret version ID.
	VersionId pulumi.StringPtrInput `pulumi:"versionId"`
}

func (GetLockBoxSecretVersionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLockBoxSecretVersionArgs)(nil)).Elem()
}

// A collection of values returned by getLockBoxSecretVersion.
type GetLockBoxSecretVersionResultOutput struct{ *pulumi.OutputState }

func (GetLockBoxSecretVersionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLockBoxSecretVersionResult)(nil)).Elem()
}

func (o GetLockBoxSecretVersionResultOutput) ToGetLockBoxSecretVersionResultOutput() GetLockBoxSecretVersionResultOutput {
	return o
}

func (o GetLockBoxSecretVersionResultOutput) ToGetLockBoxSecretVersionResultOutputWithContext(ctx context.Context) GetLockBoxSecretVersionResultOutput {
	return o
}

// List of entries in the Yandex Cloud Lockbox secret version.
func (o GetLockBoxSecretVersionResultOutput) Entries() GetLockBoxSecretVersionEntryArrayOutput {
	return o.ApplyT(func(v GetLockBoxSecretVersionResult) []GetLockBoxSecretVersionEntry { return v.Entries }).(GetLockBoxSecretVersionEntryArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetLockBoxSecretVersionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetLockBoxSecretVersionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetLockBoxSecretVersionResultOutput) SecretId() pulumi.StringOutput {
	return o.ApplyT(func(v GetLockBoxSecretVersionResult) string { return v.SecretId }).(pulumi.StringOutput)
}

func (o GetLockBoxSecretVersionResultOutput) VersionId() pulumi.StringOutput {
	return o.ApplyT(func(v GetLockBoxSecretVersionResult) string { return v.VersionId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLockBoxSecretVersionResultOutput{})
}
