// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupVpcSubnet(ctx *pulumi.Context, args *LookupVpcSubnetArgs, opts ...pulumi.InvokeOption) (*LookupVpcSubnetResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupVpcSubnetResult
	err := ctx.Invoke("yandex:index/getVpcSubnet:getVpcSubnet", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVpcSubnet.
type LookupVpcSubnetArgs struct {
	FolderId *string `pulumi:"folderId"`
	Name     *string `pulumi:"name"`
	SubnetId *string `pulumi:"subnetId"`
}

// A collection of values returned by getVpcSubnet.
type LookupVpcSubnetResult struct {
	CreatedAt   string                   `pulumi:"createdAt"`
	Description string                   `pulumi:"description"`
	DhcpOptions []GetVpcSubnetDhcpOption `pulumi:"dhcpOptions"`
	FolderId    string                   `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id           string            `pulumi:"id"`
	Labels       map[string]string `pulumi:"labels"`
	Name         string            `pulumi:"name"`
	NetworkId    string            `pulumi:"networkId"`
	RouteTableId string            `pulumi:"routeTableId"`
	SubnetId     string            `pulumi:"subnetId"`
	V4CidrBlocks []string          `pulumi:"v4CidrBlocks"`
	V6CidrBlocks []string          `pulumi:"v6CidrBlocks"`
	Zone         string            `pulumi:"zone"`
}

func LookupVpcSubnetOutput(ctx *pulumi.Context, args LookupVpcSubnetOutputArgs, opts ...pulumi.InvokeOption) LookupVpcSubnetResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupVpcSubnetResult, error) {
			args := v.(LookupVpcSubnetArgs)
			r, err := LookupVpcSubnet(ctx, &args, opts...)
			var s LookupVpcSubnetResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupVpcSubnetResultOutput)
}

// A collection of arguments for invoking getVpcSubnet.
type LookupVpcSubnetOutputArgs struct {
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	Name     pulumi.StringPtrInput `pulumi:"name"`
	SubnetId pulumi.StringPtrInput `pulumi:"subnetId"`
}

func (LookupVpcSubnetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVpcSubnetArgs)(nil)).Elem()
}

// A collection of values returned by getVpcSubnet.
type LookupVpcSubnetResultOutput struct{ *pulumi.OutputState }

func (LookupVpcSubnetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVpcSubnetResult)(nil)).Elem()
}

func (o LookupVpcSubnetResultOutput) ToLookupVpcSubnetResultOutput() LookupVpcSubnetResultOutput {
	return o
}

func (o LookupVpcSubnetResultOutput) ToLookupVpcSubnetResultOutputWithContext(ctx context.Context) LookupVpcSubnetResultOutput {
	return o
}

func (o LookupVpcSubnetResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupVpcSubnetResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupVpcSubnetResultOutput) DhcpOptions() GetVpcSubnetDhcpOptionArrayOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) []GetVpcSubnetDhcpOption { return v.DhcpOptions }).(GetVpcSubnetDhcpOptionArrayOutput)
}

func (o LookupVpcSubnetResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupVpcSubnetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupVpcSubnetResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupVpcSubnetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupVpcSubnetResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

func (o LookupVpcSubnetResultOutput) RouteTableId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.RouteTableId }).(pulumi.StringOutput)
}

func (o LookupVpcSubnetResultOutput) SubnetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.SubnetId }).(pulumi.StringOutput)
}

func (o LookupVpcSubnetResultOutput) V4CidrBlocks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) []string { return v.V4CidrBlocks }).(pulumi.StringArrayOutput)
}

func (o LookupVpcSubnetResultOutput) V6CidrBlocks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) []string { return v.V6CidrBlocks }).(pulumi.StringArrayOutput)
}

func (o LookupVpcSubnetResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcSubnetResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVpcSubnetResultOutput{})
}
