// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IotCoreDevice struct {
	pulumi.CustomResourceState

	Aliases      pulumi.StringMapOutput   `pulumi:"aliases"`
	Certificates pulumi.StringArrayOutput `pulumi:"certificates"`
	CreatedAt    pulumi.StringOutput      `pulumi:"createdAt"`
	Description  pulumi.StringPtrOutput   `pulumi:"description"`
	Name         pulumi.StringOutput      `pulumi:"name"`
	Passwords    pulumi.StringArrayOutput `pulumi:"passwords"`
	RegistryId   pulumi.StringOutput      `pulumi:"registryId"`
}

// NewIotCoreDevice registers a new resource with the given unique name, arguments, and options.
func NewIotCoreDevice(ctx *pulumi.Context,
	name string, args *IotCoreDeviceArgs, opts ...pulumi.ResourceOption) (*IotCoreDevice, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.RegistryId == nil {
		return nil, errors.New("invalid value for required argument 'RegistryId'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource IotCoreDevice
	err := ctx.RegisterResource("yandex:index/iotCoreDevice:IotCoreDevice", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIotCoreDevice gets an existing IotCoreDevice resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIotCoreDevice(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IotCoreDeviceState, opts ...pulumi.ResourceOption) (*IotCoreDevice, error) {
	var resource IotCoreDevice
	err := ctx.ReadResource("yandex:index/iotCoreDevice:IotCoreDevice", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IotCoreDevice resources.
type iotCoreDeviceState struct {
	Aliases      map[string]string `pulumi:"aliases"`
	Certificates []string          `pulumi:"certificates"`
	CreatedAt    *string           `pulumi:"createdAt"`
	Description  *string           `pulumi:"description"`
	Name         *string           `pulumi:"name"`
	Passwords    []string          `pulumi:"passwords"`
	RegistryId   *string           `pulumi:"registryId"`
}

type IotCoreDeviceState struct {
	Aliases      pulumi.StringMapInput
	Certificates pulumi.StringArrayInput
	CreatedAt    pulumi.StringPtrInput
	Description  pulumi.StringPtrInput
	Name         pulumi.StringPtrInput
	Passwords    pulumi.StringArrayInput
	RegistryId   pulumi.StringPtrInput
}

func (IotCoreDeviceState) ElementType() reflect.Type {
	return reflect.TypeOf((*iotCoreDeviceState)(nil)).Elem()
}

type iotCoreDeviceArgs struct {
	Aliases      map[string]string `pulumi:"aliases"`
	Certificates []string          `pulumi:"certificates"`
	Description  *string           `pulumi:"description"`
	Name         *string           `pulumi:"name"`
	Passwords    []string          `pulumi:"passwords"`
	RegistryId   string            `pulumi:"registryId"`
}

// The set of arguments for constructing a IotCoreDevice resource.
type IotCoreDeviceArgs struct {
	Aliases      pulumi.StringMapInput
	Certificates pulumi.StringArrayInput
	Description  pulumi.StringPtrInput
	Name         pulumi.StringPtrInput
	Passwords    pulumi.StringArrayInput
	RegistryId   pulumi.StringInput
}

func (IotCoreDeviceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iotCoreDeviceArgs)(nil)).Elem()
}

type IotCoreDeviceInput interface {
	pulumi.Input

	ToIotCoreDeviceOutput() IotCoreDeviceOutput
	ToIotCoreDeviceOutputWithContext(ctx context.Context) IotCoreDeviceOutput
}

func (*IotCoreDevice) ElementType() reflect.Type {
	return reflect.TypeOf((**IotCoreDevice)(nil)).Elem()
}

func (i *IotCoreDevice) ToIotCoreDeviceOutput() IotCoreDeviceOutput {
	return i.ToIotCoreDeviceOutputWithContext(context.Background())
}

func (i *IotCoreDevice) ToIotCoreDeviceOutputWithContext(ctx context.Context) IotCoreDeviceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IotCoreDeviceOutput)
}

// IotCoreDeviceArrayInput is an input type that accepts IotCoreDeviceArray and IotCoreDeviceArrayOutput values.
// You can construct a concrete instance of `IotCoreDeviceArrayInput` via:
//
//	IotCoreDeviceArray{ IotCoreDeviceArgs{...} }
type IotCoreDeviceArrayInput interface {
	pulumi.Input

	ToIotCoreDeviceArrayOutput() IotCoreDeviceArrayOutput
	ToIotCoreDeviceArrayOutputWithContext(context.Context) IotCoreDeviceArrayOutput
}

type IotCoreDeviceArray []IotCoreDeviceInput

func (IotCoreDeviceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IotCoreDevice)(nil)).Elem()
}

func (i IotCoreDeviceArray) ToIotCoreDeviceArrayOutput() IotCoreDeviceArrayOutput {
	return i.ToIotCoreDeviceArrayOutputWithContext(context.Background())
}

func (i IotCoreDeviceArray) ToIotCoreDeviceArrayOutputWithContext(ctx context.Context) IotCoreDeviceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IotCoreDeviceArrayOutput)
}

// IotCoreDeviceMapInput is an input type that accepts IotCoreDeviceMap and IotCoreDeviceMapOutput values.
// You can construct a concrete instance of `IotCoreDeviceMapInput` via:
//
//	IotCoreDeviceMap{ "key": IotCoreDeviceArgs{...} }
type IotCoreDeviceMapInput interface {
	pulumi.Input

	ToIotCoreDeviceMapOutput() IotCoreDeviceMapOutput
	ToIotCoreDeviceMapOutputWithContext(context.Context) IotCoreDeviceMapOutput
}

type IotCoreDeviceMap map[string]IotCoreDeviceInput

func (IotCoreDeviceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IotCoreDevice)(nil)).Elem()
}

func (i IotCoreDeviceMap) ToIotCoreDeviceMapOutput() IotCoreDeviceMapOutput {
	return i.ToIotCoreDeviceMapOutputWithContext(context.Background())
}

func (i IotCoreDeviceMap) ToIotCoreDeviceMapOutputWithContext(ctx context.Context) IotCoreDeviceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IotCoreDeviceMapOutput)
}

type IotCoreDeviceOutput struct{ *pulumi.OutputState }

func (IotCoreDeviceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IotCoreDevice)(nil)).Elem()
}

func (o IotCoreDeviceOutput) ToIotCoreDeviceOutput() IotCoreDeviceOutput {
	return o
}

func (o IotCoreDeviceOutput) ToIotCoreDeviceOutputWithContext(ctx context.Context) IotCoreDeviceOutput {
	return o
}

func (o IotCoreDeviceOutput) Aliases() pulumi.StringMapOutput {
	return o.ApplyT(func(v *IotCoreDevice) pulumi.StringMapOutput { return v.Aliases }).(pulumi.StringMapOutput)
}

func (o IotCoreDeviceOutput) Certificates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *IotCoreDevice) pulumi.StringArrayOutput { return v.Certificates }).(pulumi.StringArrayOutput)
}

func (o IotCoreDeviceOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *IotCoreDevice) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o IotCoreDeviceOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IotCoreDevice) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o IotCoreDeviceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *IotCoreDevice) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o IotCoreDeviceOutput) Passwords() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *IotCoreDevice) pulumi.StringArrayOutput { return v.Passwords }).(pulumi.StringArrayOutput)
}

func (o IotCoreDeviceOutput) RegistryId() pulumi.StringOutput {
	return o.ApplyT(func(v *IotCoreDevice) pulumi.StringOutput { return v.RegistryId }).(pulumi.StringOutput)
}

type IotCoreDeviceArrayOutput struct{ *pulumi.OutputState }

func (IotCoreDeviceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IotCoreDevice)(nil)).Elem()
}

func (o IotCoreDeviceArrayOutput) ToIotCoreDeviceArrayOutput() IotCoreDeviceArrayOutput {
	return o
}

func (o IotCoreDeviceArrayOutput) ToIotCoreDeviceArrayOutputWithContext(ctx context.Context) IotCoreDeviceArrayOutput {
	return o
}

func (o IotCoreDeviceArrayOutput) Index(i pulumi.IntInput) IotCoreDeviceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *IotCoreDevice {
		return vs[0].([]*IotCoreDevice)[vs[1].(int)]
	}).(IotCoreDeviceOutput)
}

type IotCoreDeviceMapOutput struct{ *pulumi.OutputState }

func (IotCoreDeviceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IotCoreDevice)(nil)).Elem()
}

func (o IotCoreDeviceMapOutput) ToIotCoreDeviceMapOutput() IotCoreDeviceMapOutput {
	return o
}

func (o IotCoreDeviceMapOutput) ToIotCoreDeviceMapOutputWithContext(ctx context.Context) IotCoreDeviceMapOutput {
	return o
}

func (o IotCoreDeviceMapOutput) MapIndex(k pulumi.StringInput) IotCoreDeviceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *IotCoreDevice {
		return vs[0].(map[string]*IotCoreDevice)[vs[1].(string)]
	}).(IotCoreDeviceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IotCoreDeviceInput)(nil)).Elem(), &IotCoreDevice{})
	pulumi.RegisterInputType(reflect.TypeOf((*IotCoreDeviceArrayInput)(nil)).Elem(), IotCoreDeviceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IotCoreDeviceMapInput)(nil)).Elem(), IotCoreDeviceMap{})
	pulumi.RegisterOutputType(IotCoreDeviceOutput{})
	pulumi.RegisterOutputType(IotCoreDeviceArrayOutput{})
	pulumi.RegisterOutputType(IotCoreDeviceMapOutput{})
}
