// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsMongoTargetConnectionConnectionOptions
    {
        public readonly string? AuthSource;
        public readonly string? MdbClusterId;
        public readonly Outputs.DatatransferEndpointSettingsMongoTargetConnectionConnectionOptionsOnPremise? OnPremise;
        public readonly Outputs.DatatransferEndpointSettingsMongoTargetConnectionConnectionOptionsPassword? Password;
        public readonly string? User;

        [OutputConstructor]
        private DatatransferEndpointSettingsMongoTargetConnectionConnectionOptions(
            string? authSource,

            string? mdbClusterId,

            Outputs.DatatransferEndpointSettingsMongoTargetConnectionConnectionOptionsOnPremise? onPremise,

            Outputs.DatatransferEndpointSettingsMongoTargetConnectionConnectionOptionsPassword? password,

            string? user)
        {
            AuthSource = authSource;
            MdbClusterId = mdbClusterId;
            OnPremise = onPremise;
            Password = password;
            User = user;
        }
    }
}
