// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsMongoTargetConnectionConnectionOptionsOnPremise
    {
        public readonly ImmutableArray<string> Hosts;
        public readonly int? Port;
        public readonly string? ReplicaSet;
        public readonly Outputs.DatatransferEndpointSettingsMongoTargetConnectionConnectionOptionsOnPremiseTlsMode? TlsMode;

        [OutputConstructor]
        private DatatransferEndpointSettingsMongoTargetConnectionConnectionOptionsOnPremise(
            ImmutableArray<string> hosts,

            int? port,

            string? replicaSet,

            Outputs.DatatransferEndpointSettingsMongoTargetConnectionConnectionOptionsOnPremiseTlsMode? tlsMode)
        {
            Hosts = hosts;
            Port = port;
            ReplicaSet = replicaSet;
            TlsMode = tlsMode;
        }
    }
}
