// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsClickhouseTarget
    {
        public readonly ImmutableArray<Outputs.DatatransferEndpointSettingsClickhouseTargetAltName> AltNames;
        public readonly string? CleanupPolicy;
        public readonly string? ClickhouseClusterName;
        public readonly Outputs.DatatransferEndpointSettingsClickhouseTargetConnection? Connection;
        public readonly ImmutableArray<string> SecurityGroups;
        public readonly Outputs.DatatransferEndpointSettingsClickhouseTargetSharding? Sharding;
        public readonly string? SubnetId;

        [OutputConstructor]
        private DatatransferEndpointSettingsClickhouseTarget(
            ImmutableArray<Outputs.DatatransferEndpointSettingsClickhouseTargetAltName> altNames,

            string? cleanupPolicy,

            string? clickhouseClusterName,

            Outputs.DatatransferEndpointSettingsClickhouseTargetConnection? connection,

            ImmutableArray<string> securityGroups,

            Outputs.DatatransferEndpointSettingsClickhouseTargetSharding? sharding,

            string? subnetId)
        {
            AltNames = altNames;
            CleanupPolicy = cleanupPolicy;
            ClickhouseClusterName = clickhouseClusterName;
            Connection = connection;
            SecurityGroups = securityGroups;
            Sharding = sharding;
            SubnetId = subnetId;
        }
    }
}
