// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsMysqlSource
    {
        public readonly Outputs.DatatransferEndpointSettingsMysqlSourceConnection? Connection;
        public readonly string? Database;
        public readonly ImmutableArray<string> ExcludeTablesRegexes;
        public readonly ImmutableArray<string> IncludeTablesRegexes;
        public readonly Outputs.DatatransferEndpointSettingsMysqlSourceObjectTransferSettings? ObjectTransferSettings;
        public readonly Outputs.DatatransferEndpointSettingsMysqlSourcePassword? Password;
        public readonly ImmutableArray<string> SecurityGroups;
        public readonly string? ServiceDatabase;
        public readonly string? Timezone;
        public readonly string? User;

        [OutputConstructor]
        private DatatransferEndpointSettingsMysqlSource(
            Outputs.DatatransferEndpointSettingsMysqlSourceConnection? connection,

            string? database,

            ImmutableArray<string> excludeTablesRegexes,

            ImmutableArray<string> includeTablesRegexes,

            Outputs.DatatransferEndpointSettingsMysqlSourceObjectTransferSettings? objectTransferSettings,

            Outputs.DatatransferEndpointSettingsMysqlSourcePassword? password,

            ImmutableArray<string> securityGroups,

            string? serviceDatabase,

            string? timezone,

            string? user)
        {
            Connection = connection;
            Database = database;
            ExcludeTablesRegexes = excludeTablesRegexes;
            IncludeTablesRegexes = includeTablesRegexes;
            ObjectTransferSettings = objectTransferSettings;
            Password = password;
            SecurityGroups = securityGroups;
            ServiceDatabase = serviceDatabase;
            Timezone = timezone;
            User = user;
        }
    }
}
