// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetComputeInstanceMetadataOptionsResult
    {
        public readonly int AwsV1HttpEndpoint;
        public readonly int AwsV1HttpToken;
        public readonly int GceHttpEndpoint;
        public readonly int GceHttpToken;

        [OutputConstructor]
        private GetComputeInstanceMetadataOptionsResult(
            int awsV1HttpEndpoint,

            int awsV1HttpToken,

            int gceHttpEndpoint,

            int gceHttpToken)
        {
            AwsV1HttpEndpoint = awsV1HttpEndpoint;
            AwsV1HttpToken = awsV1HttpToken;
            GceHttpEndpoint = gceHttpEndpoint;
            GceHttpToken = gceHttpToken;
        }
    }
}
