// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetCdnOriginGroupOriginResult
    {
        /// <summary>
        /// specifies whether the origin is used in its origin group as backup. A backup origin is used when one of active origins becomes unavailable.
        /// </summary>
        public readonly bool? Backup;
        /// <summary>
        /// the origin is enabled and used as a source for the CDN. Default is enabled.
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// The ID of a specific origin group.
        /// </summary>
        public readonly int OriginGroupId;
        /// <summary>
        /// IP address or Domain name of your origin and the port;
        /// </summary>
        public readonly string Source;

        [OutputConstructor]
        private GetCdnOriginGroupOriginResult(
            bool? backup,

            bool? enabled,

            int originGroupId,

            string source)
        {
            Backup = backup;
            Enabled = enabled;
            OriginGroupId = originGroupId;
            Source = source;
        }
    }
}
