// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbMongodbClusterClusterConfigAccessResult
    {
        /// <summary>
        /// Allow access for [Yandex DataLens](https://cloud.yandex.com/services/datalens).
        /// </summary>
        public readonly bool? DataLens;
        /// <summary>
        /// (Optional) Allow access for [DataTransfer](https://cloud.yandex.com/services/data-transfer)
        /// </summary>
        public readonly bool? DataTransfer;

        [OutputConstructor]
        private GetMdbMongodbClusterClusterConfigAccessResult(
            bool? dataLens,

            bool? dataTransfer)
        {
            DataLens = dataLens;
            DataTransfer = dataTransfer;
        }
    }
}
