// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMonitoringDashboardWidgetChartVisualizationSettingYaxisSettingResult
    {
        /// <summary>
        /// Left yaxis config.
        /// * `right` Right yaxis config.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetMonitoringDashboardWidgetChartVisualizationSettingYaxisSettingLeftResult> Lefts;
        public readonly ImmutableArray<Outputs.GetMonitoringDashboardWidgetChartVisualizationSettingYaxisSettingRightResult> Rights;

        [OutputConstructor]
        private GetMonitoringDashboardWidgetChartVisualizationSettingYaxisSettingResult(
            ImmutableArray<Outputs.GetMonitoringDashboardWidgetChartVisualizationSettingYaxisSettingLeftResult> lefts,

            ImmutableArray<Outputs.GetMonitoringDashboardWidgetChartVisualizationSettingYaxisSettingRightResult> rights)
        {
            Lefts = lefts;
            Rights = rights;
        }
    }
}
