// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbMongodbClusterClusterConfigMongodSecurityKmipResult
    {
        public readonly string? ClientCertificate;
        public readonly string? KeyIdentifier;
        public readonly int? Port;
        public readonly string? ServerCa;
        public readonly string? ServerName;

        [OutputConstructor]
        private GetMdbMongodbClusterClusterConfigMongodSecurityKmipResult(
            string? clientCertificate,

            string? keyIdentifier,

            int? port,

            string? serverCa,

            string? serverName)
        {
            ClientCertificate = clientCertificate;
            KeyIdentifier = keyIdentifier;
            Port = port;
            ServerCa = serverCa;
            ServerName = serverName;
        }
    }
}
