// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class AlbBackendGroupStreamBackendHealthcheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("grpcHealthcheck")]
        public Input<Inputs.AlbBackendGroupStreamBackendHealthcheckGrpcHealthcheckArgs>? GrpcHealthcheck { get; set; }

        [Input("healthcheckPort")]
        public Input<int>? HealthcheckPort { get; set; }

        [Input("healthyThreshold")]
        public Input<int>? HealthyThreshold { get; set; }

        [Input("httpHealthcheck")]
        public Input<Inputs.AlbBackendGroupStreamBackendHealthcheckHttpHealthcheckArgs>? HttpHealthcheck { get; set; }

        [Input("interval", required: true)]
        public Input<string> Interval { get; set; } = null!;

        [Input("intervalJitterPercent")]
        public Input<double>? IntervalJitterPercent { get; set; }

        [Input("streamHealthcheck")]
        public Input<Inputs.AlbBackendGroupStreamBackendHealthcheckStreamHealthcheckArgs>? StreamHealthcheck { get; set; }

        [Input("timeout", required: true)]
        public Input<string> Timeout { get; set; } = null!;

        [Input("unhealthyThreshold")]
        public Input<int>? UnhealthyThreshold { get; set; }

        public AlbBackendGroupStreamBackendHealthcheckArgs()
        {
        }
        public static new AlbBackendGroupStreamBackendHealthcheckArgs Empty => new AlbBackendGroupStreamBackendHealthcheckArgs();
    }
}
