// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class AlbLoadBalancerListenerTlsSniHandlerHandlerHttpHandlerHttp2OptionsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Maximum number of concurrent streams.
        /// </summary>
        [Input("maxConcurrentStreams")]
        public Input<int>? MaxConcurrentStreams { get; set; }

        public AlbLoadBalancerListenerTlsSniHandlerHandlerHttpHandlerHttp2OptionsArgs()
        {
        }
        public static new AlbLoadBalancerListenerTlsSniHandlerHandlerHttpHandlerHttp2OptionsArgs Empty => new AlbLoadBalancerListenerTlsSniHandlerHandlerHttpHandlerHttp2OptionsArgs();
    }
}
