// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class AlbVirtualHostRouteOptionsRbacPrincipalArgs : global::Pulumi.ResourceArgs
    {
        [Input("andPrincipals", required: true)]
        private InputList<Inputs.AlbVirtualHostRouteOptionsRbacPrincipalAndPrincipalArgs>? _andPrincipals;
        public InputList<Inputs.AlbVirtualHostRouteOptionsRbacPrincipalAndPrincipalArgs> AndPrincipals
        {
            get => _andPrincipals ?? (_andPrincipals = new InputList<Inputs.AlbVirtualHostRouteOptionsRbacPrincipalAndPrincipalArgs>());
            set => _andPrincipals = value;
        }

        public AlbVirtualHostRouteOptionsRbacPrincipalArgs()
        {
        }
        public static new AlbVirtualHostRouteOptionsRbacPrincipalArgs Empty => new AlbVirtualHostRouteOptionsRbacPrincipalArgs();
    }
}
