// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class AlbVirtualHostRouteHttpRouteArgs : global::Pulumi.ResourceArgs
    {
        [Input("directResponseAction")]
        public Input<Inputs.AlbVirtualHostRouteHttpRouteDirectResponseActionArgs>? DirectResponseAction { get; set; }

        [Input("httpMatches")]
        private InputList<Inputs.AlbVirtualHostRouteHttpRouteHttpMatchArgs>? _httpMatches;
        public InputList<Inputs.AlbVirtualHostRouteHttpRouteHttpMatchArgs> HttpMatches
        {
            get => _httpMatches ?? (_httpMatches = new InputList<Inputs.AlbVirtualHostRouteHttpRouteHttpMatchArgs>());
            set => _httpMatches = value;
        }

        [Input("httpRouteAction")]
        public Input<Inputs.AlbVirtualHostRouteHttpRouteHttpRouteActionArgs>? HttpRouteAction { get; set; }

        [Input("redirectAction")]
        public Input<Inputs.AlbVirtualHostRouteHttpRouteRedirectActionArgs>? RedirectAction { get; set; }

        public AlbVirtualHostRouteHttpRouteArgs()
        {
        }
        public static new AlbVirtualHostRouteHttpRouteArgs Empty => new AlbVirtualHostRouteHttpRouteArgs();
    }
}
