// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class ComputeInstancePlacementPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("hostAffinityRules")]
        private InputList<Inputs.ComputeInstancePlacementPolicyHostAffinityRuleGetArgs>? _hostAffinityRules;

        /// <summary>
        /// List of host affinity rules. The structure is documented below.
        /// </summary>
        public InputList<Inputs.ComputeInstancePlacementPolicyHostAffinityRuleGetArgs> HostAffinityRules
        {
            get => _hostAffinityRules ?? (_hostAffinityRules = new InputList<Inputs.ComputeInstancePlacementPolicyHostAffinityRuleGetArgs>());
            set => _hostAffinityRules = value;
        }

        /// <summary>
        /// Specifies the id of the Placement Group to assign to the instance.
        /// </summary>
        [Input("placementGroupId")]
        public Input<string>? PlacementGroupId { get; set; }

        public ComputeInstancePlacementPolicyGetArgs()
        {
        }
        public static new ComputeInstancePlacementPolicyGetArgs Empty => new ComputeInstancePlacementPolicyGetArgs();
    }
}
