// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class DatatransferEndpointSettingsKafkaTargetSerializerSerializerDebeziumGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("serializerParameters")]
        private InputList<Inputs.DatatransferEndpointSettingsKafkaTargetSerializerSerializerDebeziumSerializerParameterGetArgs>? _serializerParameters;

        /// <summary>
        /// A list of debezium parameters set by the structure of the `key` and `value` string fields.
        /// </summary>
        public InputList<Inputs.DatatransferEndpointSettingsKafkaTargetSerializerSerializerDebeziumSerializerParameterGetArgs> SerializerParameters
        {
            get => _serializerParameters ?? (_serializerParameters = new InputList<Inputs.DatatransferEndpointSettingsKafkaTargetSerializerSerializerDebeziumSerializerParameterGetArgs>());
            set => _serializerParameters = value;
        }

        public DatatransferEndpointSettingsKafkaTargetSerializerSerializerDebeziumGetArgs()
        {
        }
        public static new DatatransferEndpointSettingsKafkaTargetSerializerSerializerDebeziumGetArgs Empty => new DatatransferEndpointSettingsKafkaTargetSerializerSerializerDebeziumGetArgs();
    }
}
