// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseArgs : global::Pulumi.ResourceArgs
    {
        [Input("httpPort")]
        public Input<int>? HttpPort { get; set; }

        [Input("nativePort")]
        public Input<int>? NativePort { get; set; }

        [Input("shards")]
        private InputList<Inputs.DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseShardArgs>? _shards;
        public InputList<Inputs.DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseShardArgs> Shards
        {
            get => _shards ?? (_shards = new InputList<Inputs.DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseShardArgs>());
            set => _shards = value;
        }

        [Input("tlsMode")]
        public Input<Inputs.DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseTlsModeArgs>? TlsMode { get; set; }

        public DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseArgs()
        {
        }
        public static new DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseArgs Empty => new DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseArgs();
    }
}
