// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbMongodbClusterRestoreInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("backupId")]
        public Input<string>? BackupId { get; set; }

        [Input("time")]
        public Input<string>? Time { get; set; }

        public GetMdbMongodbClusterRestoreInputArgs()
        {
        }
        public static new GetMdbMongodbClusterRestoreInputArgs Empty => new GetMdbMongodbClusterRestoreInputArgs();
    }
}
