// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MonitoringDashboardParametrizationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("parameters")]
        private InputList<Inputs.MonitoringDashboardParametrizationParameterGetArgs>? _parameters;

        /// <summary>
        /// parameters list.
        /// </summary>
        public InputList<Inputs.MonitoringDashboardParametrizationParameterGetArgs> Parameters
        {
            get => _parameters ?? (_parameters = new InputList<Inputs.MonitoringDashboardParametrizationParameterGetArgs>());
            set => _parameters = value;
        }

        /// <summary>
        /// Selectors to select metric label values.
        /// </summary>
        [Input("selectors")]
        public Input<string>? Selectors { get; set; }

        public MonitoringDashboardParametrizationGetArgs()
        {
        }
        public static new MonitoringDashboardParametrizationGetArgs Empty => new MonitoringDashboardParametrizationGetArgs();
    }
}
