// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MonitoringDashboardWidgetChartQueryGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("downsamplings")]
        private InputList<Inputs.MonitoringDashboardWidgetChartQueryDownsamplingGetArgs>? _downsamplings;

        /// <summary>
        /// Downsamplang settings.
        /// </summary>
        public InputList<Inputs.MonitoringDashboardWidgetChartQueryDownsamplingGetArgs> Downsamplings
        {
            get => _downsamplings ?? (_downsamplings = new InputList<Inputs.MonitoringDashboardWidgetChartQueryDownsamplingGetArgs>());
            set => _downsamplings = value;
        }

        [Input("targets")]
        private InputList<Inputs.MonitoringDashboardWidgetChartQueryTargetGetArgs>? _targets;

        /// <summary>
        /// Query targets.
        /// </summary>
        public InputList<Inputs.MonitoringDashboardWidgetChartQueryTargetGetArgs> Targets
        {
            get => _targets ?? (_targets = new InputList<Inputs.MonitoringDashboardWidgetChartQueryTargetGetArgs>());
            set => _targets = value;
        }

        public MonitoringDashboardWidgetChartQueryGetArgs()
        {
        }
        public static new MonitoringDashboardWidgetChartQueryGetArgs Empty => new MonitoringDashboardWidgetChartQueryGetArgs();
    }
}
