// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Get information about a Yandex Managed PostgreSQL database. For more information, see
 * [the official documentation](https://cloud.yandex.com/docs/managed-postgresql/).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@pulumi/yandex";
 *
 * const foo = pulumi.output(yandex.getMdbPostgresqlDatabase({
 *     clusterId: "some_cluster_id",
 *     name: "test",
 * }));
 *
 * export const owner = foo.owner!;
 * ```
 */
export function getMdbPostgresqlDatabase(args: GetMdbPostgresqlDatabaseArgs, opts?: pulumi.InvokeOptions): Promise<GetMdbPostgresqlDatabaseResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("yandex:index/getMdbPostgresqlDatabase:getMdbPostgresqlDatabase", {
        "clusterId": args.clusterId,
        "deletionProtection": args.deletionProtection,
        "extensions": args.extensions,
        "lcCollate": args.lcCollate,
        "lcType": args.lcType,
        "name": args.name,
        "owner": args.owner,
        "templateDb": args.templateDb,
    }, opts);
}

/**
 * A collection of arguments for invoking getMdbPostgresqlDatabase.
 */
export interface GetMdbPostgresqlDatabaseArgs {
    /**
     * The ID of the PostgreSQL cluster.
     */
    clusterId: string;
    /**
     * Inhibits deletion of the database.
     */
    deletionProtection?: string;
    /**
     * Set of database extensions. The structure is documented below
     */
    extensions?: inputs.GetMdbPostgresqlDatabaseExtension[];
    /**
     * POSIX locale for string sorting order. Forbidden to change in an existing database.
     */
    lcCollate?: string;
    /**
     * POSIX locale for character classification. Forbidden to change in an existing database.
     */
    lcType?: string;
    /**
     * The name of the PostgreSQL cluster.
     */
    name: string;
    /**
     * Name of the user assigned as the owner of the database.
     */
    owner?: string;
    /**
     * Name of the template database.
     */
    templateDb?: string;
}

/**
 * A collection of values returned by getMdbPostgresqlDatabase.
 */
export interface GetMdbPostgresqlDatabaseResult {
    readonly clusterId: string;
    /**
     * Inhibits deletion of the database.
     */
    readonly deletionProtection?: string;
    /**
     * Set of database extensions. The structure is documented below
     */
    readonly extensions?: outputs.GetMdbPostgresqlDatabaseExtension[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * POSIX locale for string sorting order. Forbidden to change in an existing database.
     */
    readonly lcCollate: string;
    /**
     * POSIX locale for character classification. Forbidden to change in an existing database.
     */
    readonly lcType: string;
    /**
     * Name of the database extension. For more information on available extensions see [the official documentation](https://cloud.yandex.com/docs/managed-postgresql/operations/cluster-extensions).
     */
    readonly name: string;
    /**
     * Name of the user assigned as the owner of the database.
     */
    readonly owner: string;
    /**
     * Name of the template database.
     */
    readonly templateDb: string;
}

export function getMdbPostgresqlDatabaseOutput(args: GetMdbPostgresqlDatabaseOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMdbPostgresqlDatabaseResult> {
    return pulumi.output(args).apply(a => getMdbPostgresqlDatabase(a, opts))
}

/**
 * A collection of arguments for invoking getMdbPostgresqlDatabase.
 */
export interface GetMdbPostgresqlDatabaseOutputArgs {
    /**
     * The ID of the PostgreSQL cluster.
     */
    clusterId: pulumi.Input<string>;
    /**
     * Inhibits deletion of the database.
     */
    deletionProtection?: pulumi.Input<string>;
    /**
     * Set of database extensions. The structure is documented below
     */
    extensions?: pulumi.Input<pulumi.Input<inputs.GetMdbPostgresqlDatabaseExtensionArgs>[]>;
    /**
     * POSIX locale for string sorting order. Forbidden to change in an existing database.
     */
    lcCollate?: pulumi.Input<string>;
    /**
     * POSIX locale for character classification. Forbidden to change in an existing database.
     */
    lcType?: pulumi.Input<string>;
    /**
     * The name of the PostgreSQL cluster.
     */
    name: pulumi.Input<string>;
    /**
     * Name of the user assigned as the owner of the database.
     */
    owner?: pulumi.Input<string>;
    /**
     * Name of the template database.
     */
    templateDb?: pulumi.Input<string>;
}
